### ISSUE TITLE
set default palette_min and palette_max to 0

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisusJS#20]
This setting results in independent palette values for each square, but that's better than being completely blank. I tried modifying the default values in the html, but they never get set, so I'm passing it along to Steve.

**Comment by spetruzza** [comment]
Why would you set both min and max to 0? I guess that is a particular state that is just ignored by the viewer (because it is the default value of fields without any pre computed range in the metadata).

In 2d you either know and set the range or it will be set automatically only if found in the metadata (if both min and max are != 0). Different ranges on different tiles mean that no global range is being applied on the server side. Since  the pair (min 0,max 0) is ignored probably that is what is happening)

**Comment by cchriste** [comment]
The main reason is that when you don't know the ranges, the default behavior will show _something_ versus just seeing a single color.

Try it with the 72 fields of the aer1 climate dataset and you'll see why I advocate for this being the default behavior: http://aims2.llnl.gov/visus

**Comment by spetruzza** [comment]
The last commit (4e2dc017800f7d2b1707fbe335c679d59d031c3c) should allow to use 0 0 if present in the metadata. 
[Here](http://visus.org/viewer/viewer.html?server=https%3A%2F%2Faims2.llnl.gov%2Fvisus%2Fmod_visus%3F&dataset=nature_2007_aer1_hourly&field=SUANGSTR&bH=0.5828828828828829&bW=1&bX=0&bY=-0.04135463588588589&bD=0&time=0&palette=rich&palette_min=0&palette_max=0) is an example using that dataset.

Anyway this is not a solution to the general problem, the best would be to have the right values for the range in the metadata (e.g., running _visus minmax_ after the conversion).

**Comment by cchriste** [comment]
Thanks, Steve. I'm looking forward to trying it out.

As for *visus minmax, *we should create an incremental version so coarse
resolution will be quickly used in case the datasets are too big (like the
50T of climate data at LLNL).
