### ISSUE TITLE
Not clear what View/Download/Share buttons are for, and selecting them has odd effects

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisusJS#4]
For example, selecting View changes the viewport (or maybe the dataset scale, it's not apparent).

**Comment by spetruzza** [comment]
When you change resolution and click on **View** the number of samples changes and so the box that you visualize, since currently we are not using a physical box.

**Download** downloads the selected resolution of the slice/volume that you are visualizing. This does not affect the resolution of what you are visualizing. This separation between View and Download is because you could request to download the finest resolution of some dataset, but the same resolution you will not be able to render.
 
**Share** generates a link that contains the current configuration of your viewer.

I'm open to suggestions to make their more intuitive. 
An option could be to:
- open a resolution panel when you click on Download (and select the resolution that you want to download
- replace "View" with "Resolution" button that opens the same resolution panel to select the resolution (for visualization)

**Comment by cchriste** [comment]
The new viewer UI seems much more intuitive with regard to these features. Closing the issue.
